### ISSUE TITLE
Create issues in Parquet format

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/digital-land-python#262]
**Overview**

Create issues in Parquet format as well as the existing CSV and SQLite formats.

**Background**
Following the [design proposal for an internal API](https://digital-land.github.io/technical-documentation/architecture-and-infrastructure/proposals/010-data-pipeline-api/ "‌"), we would like to prove some technology choices which include the use of Fast API with DuckDB accessing Parquet on S3.

This work was identified during the [spike on API design](https://trello.com/c/NAhFxEFo/3561-spike-api-design-requirements "‌").

By writing issues in Parquet format, the foundation will be laid to prove whether Parquet will be an appropriate format for both consuming via an internal API and Datasette.

**Tech Approach**

- Change digital-land-python to write issues in Parquet format
- Ensure new Parquet file is uploaded to S3 alongside the CSV and SQLite versions
- Write a test case

**Acceptance Criteria/Tests**

- Code merged within digital-land-python repo
- Revised pipeline deployed to production

---

**Ticket Management - DELETE** this section once completed

- Complete all relevant tags - make sure Infrastructure is tagged so it is picked up by our filters!
- Complete the time estimate field
- Make sure you have a PR link in the Overviewabove.
- If relevant, link to the relevant OKR as an attachment.
- Link to any tickets in other boards that are dependent on it.

**Comment by CarlosCoelhoSL** [comment]
The above PRs can be merged on Monday when approved
