### ISSUE TITLE
Add Data Command - Process Resource (#2)

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/digital-land-python#308]
**Overview**
- See full overview in this Mural: https://app.mural.co/t/mhclg2837/m/mhclg2837/1715695232673/731cd7c340728327108245664ddca4e6a27b95b7
- We want to build on the `add-data` command we have made in digital-land/digital-land-python#284 as well as continue building acceptance tests for this command to ensure that future updates to the pipeline do not break this command.

**Tech Approach**
- For all these tickets, you should try and pair with one of the DM developers so that they can understand the code, advise on their working practices and (hopefully) take on some of the ongoing maintenance for it after implementation.
- Following previous ticket, we add a breakpoint to the command that asks the user whether they want to continue or not. At this point, they may want to select 'no' (in order to change config etc). At this point, the command will abort and delete any logs created.
- If the user selects 'yes', then the command will attempt to process the resource through the pipeline, saving both the converted and transformed resources. 
- If the resource fails to process correctly (e.g. no reference column mapped, processing error), we will throw an error and print a summary to the console.
- If the resource processes correctly, then we print to the console:
    - success / failure processing resource
    - summary of the field-column mappings that have been made (mapped columns, unmapped columns, unmapped fields)    
    - entity summary: count of existing entities, new (unassigned) entities, and warning if no new entities
    - warning if no reference field in mappings
    - paths to the converted and transformed resource csv's

**Acceptance Criteria**
- Digital Land command `add-data` can now process the resource and report back a summary of the processing
- Acceptance tests that show if successful then resource is downloaded. If unsuccessful, command is exited and update to console log on why.
- Unit and/or integration tests added for any new (or altered) pieces of code.
- Testing by DM before going live.

**Comment by CarlosCoelhoSL** [comment]
Update: Owen's comments have been actioned on.
Swati has requested one additional check in the entity summary - I'm just wrapping this up and writing tests for it now. Will message Owen when ready for re-review
